version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    container_name: frontend-container
    networks:
      - mern-networks
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 5555:5555
    container_name: backend-container
    networks:
      - mern-networks
    depends_on:
      - mongo 

networks:
  mern-networks:
    driver: bridge
